## Arrays

In [1]:
# creating an array
import numpy as pd
a1 = pd.array([1, 2, 3, 4, 5])
a1

array([1, 2, 3, 4, 5])

In [4]:
#Printing shape of an array
print("Array Shape", a1.shape)

Array Shape (5,)


In [5]:
#printing type of an array
print("Array Shape", a1.dtype)

Array Shape int32


In [7]:
# Creating 3*3 arrays
a2= pd.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:

a2.shape

(3, 3)

In [10]:
#creating an array of 2*4 zero array
a3 = pd.zeros((2,4))
a3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# creating an 2*4 array with all values as 1
a4 = pd.ones((2,4))
a4


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#creating an 3*3 identity matrix
a5 =pd.identity(3)
a5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
a6 = pd.random.randn(3,4)
a6

array([[ 1.73926743, -0.63725916,  0.38827394,  0.32832721],
       [-0.94055824, -0.51730016, -0.47213304, -0.55122894],
       [-0.61369345,  1.24156507, -0.33087945, -1.77879113]])

In [21]:
from io import BytesIO
b = BytesIO(b"2:3:4\n5:6:7\n8:9:1")
a = pd.genfromtxt(b ,delimiter=":")
a

array([[2., 3., 4.],
       [5., 6., 7.],
       [8., 9., 1.]])

## Accessing array Elements
### Simple Indexing

In [22]:
#Accessing row 1 from above array a
a[1]

array([5., 6., 7.])

In [25]:
#printing two arrays of 2*3 matrices with range 0-12
a = pd.arange(12).reshape(2,2,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [26]:
#accessing 0th matrix from above set of matrices
a[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
# printing array wih range 0-10 from value after 5th position
a = pd.arange(10)
a[5:]

array([5, 6, 7, 8, 9])

In [28]:
#printing values before 5th position
a[:-5]

array([0, 1, 2, 3, 4])

In [30]:
#creating set of 2*3 matrices 
a = pd.arange(12).reshape(2,2,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [31]:
#accessing elements of 1st matrix from above set
a[1:2]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [33]:
a = pd.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
#accessing 3rd column of all the 3 matrices
a[:,:,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

#### Advanced Indexing

In [35]:
a = pd.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
# accessing 0th row 1 column at 0th position
# then 1 row 0th column element at 1st position
# then 2 row 0th column element at 2 nd Position
a[[0,1,2],[1,0,0]]

array([1, 3, 6])

##### Boolean Indexing

In [39]:
# initialising an array with cities name and creating another matrix of 5*3 with random values
cities = pd.array(["delhi","banglaore","mumbai","chennai","bhopal"])
city_data = pd.random.randn(5,3)
city_data

array([[-0.5150905 , -0.02673596,  0.42450674],
       [-0.44633013,  0.27406028,  0.98530106],
       [ 0.29293496, -0.5347332 ,  0.90478945],
       [ 0.86224955,  0.93212413, -0.78336833],
       [-0.55765764, -0.65801347, -0.70546626]])

In [40]:
# accessing elements from above matrix with random values that matches the position of delhi the element from another array
city_data[cities =="delhi"]

array([[-0.5150905 , -0.02673596,  0.42450674]])

In [41]:
#accesing all the elements with values greater than zero
city_data[city_data >0]

array([0.42450674, 0.27406028, 0.98530106, 0.29293496, 0.90478945,
       0.86224955, 0.93212413])

In [42]:
# assigning value 0 to all the elements with values greater than 0
city_data[city_data >0] = 0
city_data

array([[-0.5150905 , -0.02673596,  0.        ],
       [-0.44633013,  0.        ,  0.        ],
       [ 0.        , -0.5347332 ,  0.        ],
       [ 0.        ,  0.        , -0.78336833],
       [-0.55765764, -0.65801347, -0.70546626]])

#### Operations on Arrays

In [43]:
arr = pd.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
#Adding 5 to all the elements
arr + 5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
# multipyling all the elements with 3
arr * 3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42]])

In [48]:
a1 = pd.arange(15).reshape(5,3)
a2 = pd.arange(5).reshape(5,1)
a2+a1

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [49]:
arr1 = pd.random.randn(5,3)
arr1

array([[ 1.38161699,  0.98215975, -0.30794748],
       [-0.48235721, -1.20459715,  0.70332208],
       [ 0.61677421, -2.58329026,  0.5793761 ],
       [-0.06806257,  0.27917434,  1.44109669],
       [-0.24889253,  0.10165273,  0.40024023]])

In [51]:
#getting the integer and decimal parts of the above array in two different matrices
pd.modf(arr1)

(array([[ 0.38161699,  0.98215975, -0.30794748],
        [-0.48235721, -0.20459715,  0.70332208],
        [ 0.61677421, -0.58329026,  0.5793761 ],
        [-0.06806257,  0.27917434,  0.44109669],
        [-0.24889253,  0.10165273,  0.40024023]]), array([[ 1.,  0., -0.],
        [-0., -1.,  0.],
        [ 0., -2.,  0.],
        [-0.,  0.,  1.],
        [-0.,  0.,  0.]]))

### Linear algebra using numpy

In [52]:
Dot multiplication of two matrices
A = pd.array([[1,2,3],[4,5,6],[7,8,9]])
B = pd.array([[9,8,7],[6,5,4],[1,2,3]])
A.dot(B)

array([[ 24,  24,  24],
       [ 72,  69,  66],
       [120, 114, 108]])

In [54]:
#Transposing the matrix from 3,5 to 5,3
A = pd.arange(15).reshape(3,5)
A.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [55]:
#Calulating SVD
pd.linalg.svd(A)

(array([[-0.15425367,  0.89974393,  0.40824829],
        [-0.50248417,  0.28432901, -0.81649658],
        [-0.85071468, -0.3310859 ,  0.40824829]]),
 array([3.17420265e+01, 2.72832424e+00, 3.59372947e-16]),
 array([[-0.34716018, -0.39465093, -0.44214167, -0.48963242, -0.53712316],
        [-0.69244481, -0.37980343, -0.06716206,  0.24547932,  0.55812069],
        [-0.41088392,  0.70864929,  0.02536563, -0.53314345,  0.21001245],
        [-0.40770221,  0.39487291, -0.09099898,  0.62818809, -0.5243598 ],
        [ 0.25485938,  0.20467429, -0.8894244 ,  0.14538841,  0.28450232]]))

In [56]:
a = pd.array([[7,5,-3], [3,-5,2],[5,3,-7]])
b = pd.array([16,-8,0])
x = pd.linalg.solve(a, b)
x

array([1., 3., 2.])

In [57]:
pd.allclose(pd.dot(a, x), b)

True

# Pandas
## Data frames

In [3]:
#preparaing the data frame with city name and numerical data corresponding to these cities
import pandas as pd
d =  [{'city':'Delhi',"data":1000},
      {'city':'Banglaore',"data":2000},
      {'city':'Mumbai',"data":1000}]
pd.DataFrame(d)

city  data
0      Delhi  1000
1  Banglaore  2000
2     Mumbai  1000

In [4]:
city_data = pd.read_csv(r'C:\Users\asus\practical-ml-w-python-master\Code_Ch 02\code\simplemaps-worldcities-basic.csv')

In [5]:
#to fetch top first 10 rows
city_data.head(n=10)

city      city_ascii        lat        lng       pop  \
0   Qal eh-ye Now       Qal eh-ye  34.983000  63.133300    2997.0   
1     Chaghcharan     Chaghcharan  34.516701  65.250001   15000.0   
2     Lashkar Gah     Lashkar Gah  31.582998  64.360000  201546.0   
3          Zaranj          Zaranj  31.112001  61.886998   49851.0   
4      Tarin Kowt      Tarin Kowt  32.633298  65.866699   10000.0   
5    Zareh Sharan    Zareh Sharan  32.850000  68.416705   13737.0   
6        Asadabad        Asadabad  34.866000  71.150005   48400.0   
7         Taloqan         Taloqan  36.729999  69.540004   64256.0   
8  Mahmud-E Eraqi  Mahmud-E Eraqi  35.016696  69.333301    7407.0   
9      Mehtar Lam      Mehtar Lam  34.650000  70.166701   17345.0   

       country iso2 iso3 province  
0  Afghanistan   AF  AFG  Badghis  
1  Afghanistan   AF  AFG     Ghor  
2  Afghanistan   AF  AFG  Hilmand  
3  Afghanistan   AF  AFG   Nimroz  
4  Afghanistan   AF  AFG  Uruzgan  
5  Afghanistan   AF  AFG  Paktika  
6  Afghanistan   AF  AFG    Kunar  
7  Afghanistan   AF  AFG   Takhar  
8  Afghanistan   AF  AFG   Kapisa  
9  Afghanistan   AF  AFG  Laghman

In [6]:
#fetching last 5 rows using tail function
city_data.tail()

city   city_ascii        lat        lng        pop   country  \
7317       Mutare       Mutare -18.970019  32.650038   216785.0  Zimbabwe   
7318       Kadoma       Kadoma -18.330006  29.909947    56400.0  Zimbabwe   
7319  Chitungwiza  Chitungwiza -18.000001  31.100003   331071.0  Zimbabwe   
7320       Harare       Harare -17.817790  31.044709  1557406.5  Zimbabwe   
7321     Bulawayo     Bulawayo -20.169998  28.580002   697096.0  Zimbabwe   

     iso2 iso3          province  
7317   ZW  ZWE        Manicaland  
7318   ZW  ZWE  Mashonaland West  
7319   ZW  ZWE            Harare  
7320   ZW  ZWE            Harare  
7321   ZW  ZWE          Bulawayo

In [7]:
series_es = city_data.lat

In [8]:
type(series_es)

pandas.core.series.Series

In [9]:
# fetch data from first 10 rows starting from 1 row with alternate values
series_es[1:10:2]

1    34.516701
3    31.112001
5    32.850000
7    36.729999
9    34.650000
Name: lat, dtype: float64

In [10]:
series_es[:7]

0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
Name: lat, dtype: float64

In [11]:
series_es[:-7315]

0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
Name: lat, dtype: float64

In [12]:
city_data[:7]

city    city_ascii        lat        lng       pop      country  \
0  Qal eh-ye Now     Qal eh-ye  34.983000  63.133300    2997.0  Afghanistan   
1    Chaghcharan   Chaghcharan  34.516701  65.250001   15000.0  Afghanistan   
2    Lashkar Gah   Lashkar Gah  31.582998  64.360000  201546.0  Afghanistan   
3         Zaranj        Zaranj  31.112001  61.886998   49851.0  Afghanistan   
4     Tarin Kowt    Tarin Kowt  32.633298  65.866699   10000.0  Afghanistan   
5   Zareh Sharan  Zareh Sharan  32.850000  68.416705   13737.0  Afghanistan   
6       Asadabad      Asadabad  34.866000  71.150005   48400.0  Afghanistan   

  iso2 iso3 province  
0   AF  AFG  Badghis  
1   AF  AFG     Ghor  
2   AF  AFG  Hilmand  
3   AF  AFG   Nimroz  
4   AF  AFG  Uruzgan  
5   AF  AFG  Paktika  
6   AF  AFG    Kunar

In [13]:
# first 5 rows and 4 columns
city_data.iloc[:5,:4]

city   city_ascii        lat        lng
0  Qal eh-ye Now    Qal eh-ye  34.983000  63.133300
1    Chaghcharan  Chaghcharan  34.516701  65.250001
2    Lashkar Gah  Lashkar Gah  31.582998  64.360000
3         Zaranj       Zaranj  31.112001  61.886998
4     Tarin Kowt   Tarin Kowt  32.633298  65.866699

In [14]:
city_data[city_data['pop'] > 10000000][city_data.columns[pd.Series(city_data.columns).str.startswith('l')]]

lat         lng
360  -34.602502  -58.397531
1171 -23.558680  -46.625020
2068  31.216452  121.436505
3098  28.669993   77.230004
3110  19.016990   72.856989
3492  35.685017  139.751407
4074  19.442442  -99.130988
4513  24.869992   66.990009
5394  55.752164   37.615523
6124  41.104996   29.010002
7071  40.749979  -73.980017

In [15]:
city_greater_10mil = city_data[city_data['pop'] > 10000000]
city_greater_10mil.rename(columns={'pop':'population'}, inplace=True)
city_greater_10mil.where(city_greater_10mil.population > 15000000)

C:\Users\asus\Anaconda3\lib\site-packages\pandas\core\frame.py:4025: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)


city city_ascii        lat         lng  population country iso2 iso3  \
360      NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
1171     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
2068     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
3098     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
3110  Mumbai     Mumbai  19.016990   72.856989  15834918.0   India   IN  IND   
3492   Tokyo      Tokyo  35.685017  139.751407  22006299.5   Japan   JP  JPN   
4074     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
4513     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
5394     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
6124     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   
7071     NaN        NaN        NaN         NaN         NaN     NaN  NaN  NaN   

         province  
360           NaN  
1171          NaN  
2068          NaN  
3098          NaN  
3110  Maharashtra  
3492        Tokyo  
4074          NaN  
4513          NaN  
5394          NaN  
6124          NaN  
7071          NaN

In [17]:
df = pd.DataFrame(pd.random.randn(8, 3),
columns=['A', 'B', 'C'])

AttributeError: module 'pandas' has no attribute 'random'

In [19]:
import numpy as np
df = pd.DataFrame(np.random.randn(8, 3),
columns=['A', 'B', 'C'])

In [20]:
nparray = df.values
type(nparray)

numpy.ndarray

In [21]:
#places nan to the position 4,2
from numpy import nan
df.iloc[4,2] = nan

In [22]:
df

A         B         C
0 -0.150695 -0.613713  1.471554
1 -0.106338 -0.924962  0.229252
2  0.507356 -1.030840 -0.310388
3 -0.032826 -1.336683  1.177309
4 -0.793647  0.905774       NaN
5  1.041086 -0.052197  1.515336
6  0.195814 -0.607814  0.174284
7 -1.299199 -0.291105  1.169789

In [23]:
#put 0 where there is no data
df.fillna(0)

A         B         C
0 -0.150695 -0.613713  1.471554
1 -0.106338 -0.924962  0.229252
2  0.507356 -1.030840 -0.310388
3 -0.032826 -1.336683  1.177309
4 -0.793647  0.905774  0.000000
5  1.041086 -0.052197  1.515336
6  0.195814 -0.607814  0.174284
7 -1.299199 -0.291105  1.169789

In [24]:
#assigning lat,long,pop to columns_numeric variable
columns_numeric = ['lat','lng','pop']

In [25]:
#calculating mean
city_data[columns_numeric].mean()

lat        20.662876
lng        10.711914
pop    265463.071633
dtype: float64

In [26]:
#calculating sum
city_data[columns_numeric].sum()

lat    1.512936e+05
lng    7.843263e+04
pop    1.943721e+09
dtype: float64

In [27]:
#calculating count
city_data[columns_numeric].count()

lat    7322
lng    7322
pop    7322
dtype: int64

In [28]:
#calculating median
city_data[columns_numeric].median()

lat       26.792730
lng       18.617509
pop    61322.750000
dtype: float64

In [29]:
#calculate quantile
city_data[columns_numeric].quantile(0.8)

lat        46.852480
lng        89.900018
pop    269210.000000
Name: 0.8, dtype: float64

In [30]:
city_data[columns_numeric].sum(axis = 1).head()

0      3095.116300
1     15099.766702
2    201641.942998
3     49943.998999
4     10098.499997
dtype: float64

In [31]:
#describe the data for coumn numeric with lat,lng,pop
city_data[columns_numeric].describe()

lat          lng           pop
count  7322.000000  7322.000000  7.322000e+03
mean     20.662876    10.711914  2.654631e+05
std      29.134818    79.044615  8.287622e+05
min     -89.982894  -179.589979 -9.900000e+01
25%      -0.324710   -64.788472  1.734425e+04
50%      26.792730    18.617509  6.132275e+04
75%      43.575448    73.103628  2.001726e+05
max      82.483323   179.383304  2.200630e+07

In [32]:
city_data1 = city_data.sample(3)

#### Concatinating 

In [33]:
#concarinating cit_data1 and city_data2
city_data2 = city_data.sample(3)
city_data_combine = pd.concat([city_data1,city_data2])
city_data_combine

city    city_ascii        lat        lng       pop  \
6729       Decatur       Decatur  39.840706 -88.954736   74967.5   
5533   Komatipoort   Komatipoort -25.409574  31.940004   10333.5   
7162     Barcelona     Barcelona  10.130375 -64.720014  361430.0   
6795  Wilkes Barre  Wilkes Barre  41.249044 -75.877937   99824.5   
2819          Boke          Boke  10.939990 -14.299990  116270.0   
607          Agdam         Agdam  40.905278  45.556389       0.0   

                       country iso2 iso3      province  
6729  United States of America   US  USA      Illinois  
5533              South Africa   ZA  ZAF    Mpumalanga  
7162                 Venezuela   VE  VEN    Anzoátegui  
6795  United States of America   US  USA  Pennsylvania  
2819                    Guinea   GN  GIN          Boke  
607                 Azerbaijan   AZ  AZE         Tovuz

In [34]:
df1 = pd.DataFrame({'col1': ['col10', 'col11', 'col12', 'col13'],
                    'col2': ['col20', 'col21', 'col22', 'col23'],
                    'col3': ['col30', 'col31', 'col32', 'col33'],
                    'col4': ['col40', 'col41', 'col42', 'col43']},
                   index=[0, 1, 2, 3])

In [35]:
df

A         B         C
0 -0.150695 -0.613713  1.471554
1 -0.106338 -0.924962  0.229252
2  0.507356 -1.030840 -0.310388
3 -0.032826 -1.336683  1.177309
4 -0.793647  0.905774       NaN
5  1.041086 -0.052197  1.515336
6  0.195814 -0.607814  0.174284
7 -1.299199 -0.291105  1.169789

In [37]:
df4 = pd.DataFrame({'col2': ['col22', 'col23', 'col26', 'col27'],
                    'Col4': ['Col42', 'Col43', 'Col46', 'Col47'],
                    'col6': ['col62', 'col63', 'col66', 'col67']},
                   index=[2, 3, 6, 7])

pd.concat([df1,df4], axis=1)

col1   col2   col3   col4   col2   Col4   col6
0  col10  col20  col30  col40    NaN    NaN    NaN
1  col11  col21  col31  col41    NaN    NaN    NaN
2  col12  col22  col32  col42  col22  Col42  col62
3  col13  col23  col33  col43  col23  Col43  col63
6    NaN    NaN    NaN    NaN  col26  Col46  col66
7    NaN    NaN    NaN    NaN  col27  Col47  col67

In [38]:
#drop duplicates for iso3 and country
country_data = city_data[['iso3','country']].drop_duplicates()

In [39]:
#returns shape
country_data.shape

(223, 2)

In [40]:
#return top 5 rows
country_data.head()

iso3         country
0    AFG     Afghanistan
33   ALD           Aland
34   ALB         Albania
60   DZA         Algeria
111  ASM  American Samoa

In [41]:
del(city_data['country'])

In [42]:
city_data.merge(country_data, 'inner').head()

city   city_ascii        lat        lng       pop iso2 iso3  \
0  Qal eh-ye Now    Qal eh-ye  34.983000  63.133300    2997.0   AF  AFG   
1    Chaghcharan  Chaghcharan  34.516701  65.250001   15000.0   AF  AFG   
2    Lashkar Gah  Lashkar Gah  31.582998  64.360000  201546.0   AF  AFG   
3         Zaranj       Zaranj  31.112001  61.886998   49851.0   AF  AFG   
4     Tarin Kowt   Tarin Kowt  32.633298  65.866699   10000.0   AF  AFG   

  province      country  
0  Badghis  Afghanistan  
1     Ghor  Afghanistan  
2  Hilmand  Afghanistan  
3   Nimroz  Afghanistan  
4  Uruzgan  Afghanistan

#### Scikit Learn

In [43]:
from sklearn import datasets
diabetes = datasets.load_diabetes()
X = diabetes.data[:10]
y = diabetes.target

In [44]:
X[:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567061, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286377, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02269202, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187235,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03199144, -0.04664087]])

In [45]:
y[:10]

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310.])

In [46]:
feature_names=['age', 'sex', 'bmi', 'bp',
               's1', 's2', 's3', 's4', 's5', 's6']

##### Scikit Regression

In [47]:
from sklearn import datasets
from sklearn.linear_model import Lasso

from sklearn import linear_model, datasets
from sklearn.model_selection import GridSearchCV

diabetes = datasets.load_diabetes()
X_train = diabetes.data[:310]
y_train = diabetes.target[:310]

X_test = diabetes.data[310:]
y_test = diabetes.target[310:]

lasso = Lasso(random_state=0)
alphas = np.logspace(-4, -0.5, 30)

scores = list()
scores_std = list()

estimator = GridSearchCV(lasso,
                         param_grid = dict(alpha=alphas))

estimator.fit(X_train, y_train)

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=0,
   selection='cyclic', tol=0.0001, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'alpha': array([1.00000e-04, 1.32035e-04, 1.74333e-04, 2.30181e-04, 3.03920e-04,
       4.01281e-04, 5.29832e-04, 6.99564e-04, 9.23671e-04, 1.21957e-03,
       1.61026e-03, 2.12611e-03, 2.80722e-03, 3.70651e-03, 4.89390e-03,
       6.46167e-03, 8.53168e-03, 1.12648e-02, 1.48735e-02, 1.96383e-02,
       2.59294e-02, 3.42360e-02, 4.52035e-02, 5.96846e-02, 7.88046e-02,
       1.04050e-01, 1.37382e-01, 1.81393e-01, 2.39503e-01, 3.16228e-01])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [48]:
#estimating best score
estimator.best_score_

0.4654063759023531

In [49]:
estimator.best_estimator_

Lasso(alpha=0.02592943797404667, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=False, positive=False, precompute=False,
   random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

In [50]:
#predicting x score
estimator.predict(X_test)

array([203.42104984, 177.6595529 , 122.62188598, 212.81136958,
       173.61633075, 114.76145025, 202.36033584, 171.70767813,
       164.28694562, 191.29091477, 191.41279009, 288.2772433 ,
       296.47009002, 234.53378413, 210.61427168, 228.62812055,
       156.74489991, 225.08834492, 191.75874632, 102.81600989,
       172.373221  , 111.20843429, 290.22242876, 178.64605207,
        78.13722832,  86.35832297, 256.41378529, 165.99622543,
       121.29260976, 153.48718848, 163.09835143, 180.0932902 ,
       161.4330553 , 155.80211635, 143.70181085, 126.13753819,
       181.06471818, 105.03679977, 131.0479936 ,  90.50606427,
       252.66486639,  84.84786067,  59.41005358, 184.51368208,
       201.46598714, 129.96333913,  90.65641478, 200.10932516,
        55.2884802 , 171.60459062, 195.40750666, 122.14139787,
       231.72783897, 159.49750022, 160.32104862, 165.53701866,
       260.73217736, 259.77213787, 204.69526082, 185.66480969,
        61.09821961, 209.9214333 , 108.50410841, 141.18

#### Neural Network Frameworks

#### Theano Examples

In [1]:
import numpy
import theano.tensor as T
from theano import function
x = T.dscalar('x')
y = T.dscalar('y')
z = x + y

ModuleNotFoundError: No module named 'theano'

In [52]:
f = function([x, y], z)
f(8, 2)

NameError: name 'function' is not defined